### ISSUE TITLE
Whitespace before a closing ] breaks fixing unclosed nested arrays

### ISSUE THREAD

**Issue by brettrp** [mangiucugna/json_repair#1]
**Describe the bug**

JSON like this:

```json
[[1 ]
```

produces an `Invalid JSON format` exception instead of repairing the JSON.  It's the trailing whitespace that is the problem; this:

```json
[[1]
```

is fine.

(This is a reduced version of JSON produced by ChatGPT where the original error occurred.)

**To Reproduce**
Try fixing the above JSON.

Note that there are two related issues:
- the code only checks for space (not other whitespace like carriage returns)
- space at the end of an array is not handled

**Additional context**
PR which fixes this coming shortly.

**Comment by brettrp** [comment]
I have a PR which fixes this but don't have permission to create a branch ....

**Comment by mangiucugna** [comment]
First of all, thanks so much for contributing!

tbh I have no idea what's the safest way to allow anybody to create a PR, for now I just invited you to the repository so you can push your branch. Once it's there, I will review, build and publish a new minor version with the fix
