### ISSUE TITLE
Infinite loop when key is empty

### ISSUE THREAD

**Issue by jenniferhaefner** [mangiucugna/json_repair#11]
Hi, first of all, thanks for this very useful library! 
My model occasionally produces JSON strings with empty keys, so I encountered the following issue:

**Describe the bug**
When a key in the JSON string is empty, the library runs into an infinite loop in 'parse_object'.

**To Reproduce**
1. Call 'repair_json' with a key in the JSON string being empty,
    for example: repair_json("{'': 'test'}")

**Expected behavior**
Either return 'Invalid JSON format' or substitute the empty key? Not sure what's best here

**Comment by AnshSinghSonkhia** [comment]
It seems like you're dealing with an issue where your JSON parsing library runs into an infinite loop when it encounters a JSON string with an empty key. To resolve this issue, you might want to consider modifying your `repair_json` function to handle such cases appropriately. Here's a suggestion:

```python
import json

def repair_json(json_str):
    try:
        # Attempt to load the JSON string
        data = json.loads(json_str)

        # Check if the parsed data is a dictionary
        if isinstance(data, dict):
            # Check for empty keys in the dictionary
            empty_keys = [key for key in data.keys() if not key]
            if empty_keys:
                # If there are empty keys, handle it appropriately
                for key in empty_keys:
                    # You can choose to remove the key or replace it with a default value
                    # For example, replacing it with the string 'EMPTY_KEY'
                    data['EMPTY_KEY'] = data.pop(key)
                return data
            else:
                # If there are no empty keys, return the original data
                return data
        else:
            # If the parsed data is not a dictionary, return an error message
            return 'Invalid JSON format'

    except json.JSONDecodeError as e:
        # Handle JSON decoding errors
        return f'Error decoding JSON: {str(e)}'

# Example usage
result = repair_json("{'': 'test'}")
print(result)
```

In this example, if the JSON string contains a dictionary with empty keys, the function iterates over the empty keys and replaces them with a default key (e.g., 'EMPTY_KEY'). You can customize this behavior based on your specific requirements, whether it's removing the empty key, replacing it, or handling it differently. If the JSON string is not a dictionary, the function returns an error message indicating an invalid JSON format.

**Comment by mangiucugna** [comment]
I have removed the GPT generated comment, blimey what a world we live in eh

Second, good catch!
I will add the string to the tests and solve the loop, an empty string is in fact a valid key in JSON (weird eh?)

**Comment by mangiucugna** [comment]
no sorry, I need to use a placeholder or it will break when returning an object

**Comment by mangiucugna** [comment]
These are the two tests added:

assert {
        repair_json('{"" : true, "key2": "value2"}') == '{" ": true, "key2": "value_2"}'
    }
    assert {
        repair_json('{"": true, "key2": "value2"}') == '{"empty_placeholder": true, "key2": "value_2"}'
    }
    
    I will release 0.5.1 now with this fix

**Comment by jenniferhaefner** [comment]
Great, thank you!
