### ISSUE TITLE
Removing markdown code blocks?

### ISSUE THREAD

**Issue by Manouchehri** [mangiucugna/json_repair#13]
Sometimes I've gotten responses from LLMs that look like this:

````
```json
{
  "msg": "test"
}
```
````

and this: 

````
```
{
  "msg": "test"
}
```
````

Do you think it makes sense to add markdown backtick stripping to this library? =)

**Comment by Manouchehri** [comment]
@mangiucugna You're awesome. Thank you!

**Comment by mangiucugna** [comment]
My objective here is to support everything, so I am releasing 0.7.0 to support this use case as well :)
