### ISSUE TITLE
Missing left quotes in numbers are not parsed properly

### ISSUE THREAD

**Issue by AloXado320** [mangiucugna/json_repair#23]
**Describe the bug**
If there's a missing out quote at the left of a json define, it doesn't repair properly

**To Reproduce**
Run this json file with `json_repair`
```
{
  "words": abcdef",
  "numbers": 12345",
  "words2": ghijkl"
}
```

Gets parsed like this

`{'words': 'abcdef', 'numbers': 12345, ',\n  ': 'ords2', 'ghijkl': ''}`

**Expected behavior**
Proper output:
`{'words': 'abcdef', 'numbers': '12345', 'words2': 'ghijkl'}`

**Comment by mangiucugna** [comment]
Hi! Thank for reporting the bug, one note about numbers in canonical JSON though. The expected output here is:

`{ "words": "abcdef", "numbers": 12345, "words2": "ghijkl" }`

So the library should fix this by removing the dangling `"` and not eating the following key
