### ISSUE TITLE
exchange of a friendly link request

### ISSUE THREAD

**Issue by RealAlexandreAI** [mangiucugna/json_repair#25]
Hello,

I would like to extend my gratitude for the exceptional project you have created. Inspired by your work, I have developed a Go language version of json-repair, which can be found at https://github.com/RealAlexandreAI/json-repair. With the aim of fostering a collaborative development environment and providing developers with access to libraries in various programming languages, I propose the exchange of a friendly link between our projects.

This initiative is particularly relevant in addressing the challenge of handling the chaotic JSON strings often generated by Large Language Models (LLMs). By linking our repositories, we can offer a more comprehensive solution to the developer community, enabling them to effectively manage and repair JSON data across different platforms and programming languages.

I look forward to your positive response and the potential benefits that such a collaboration could bring to both our projects and their users.

**Comment by mangiucugna** [comment]
Hi, sure thing. I added a section in my README.md as you can see from the commit
