### ISSUE TITLE
Adding missing escape for double quote

### ISSUE THREAD

**Issue by nikolaysm** [mangiucugna/json_repair#26]
Hi @mangiucugna,

Thank you for your efforts on this. I've encountered a similar issue with the output from the LLM. It seems that the `repair_json` function isn't handling certain cases correctly.

For instance, when trying to repair the following JSON string:
```
json_str = '{\n"html": "<h3 id="title">Waarom meer dan 200 Technical Experts - "Passie voor techniek"?</h3>"}'
data = repair_json(json_str, return_objects=True)
```

The current output is:
```
{
    'html': '<h3 id=', 
    'techniek': 'h3>',
    'title': u'Waarom meer dan 200 Technical Experts - '
}
```
However, the expected output should be:

```
{
    'html': '<h3 id="title">Waarom meer dan 200 Technical Experts - "Passie voor techniek"?</h3>'
}
```

It seems like the function is having trouble handling certain characters or nested structures properly. Would you mind looking into this further?

Thank you again for your attention to this matter.

_Originally posted by @nikolaysm in https://github.com/mangiucugna/json_repair/issues/20#issuecomment-2066249721_

**Comment by nikolaysm** [comment]
We might consider expanding the logic to detect the closing quote. 

A similar approach is discussed here: https://github.com/josdejong/jsonrepair/pull/116

**Comment by mangiucugna** [comment]
good point, let me try something although I am not sure how it would interact with all the other use cases but is worth a try

**Comment by mangiucugna** [comment]
Thanks for pointing me in the right direction, I am releasing 0.14.0 with this fix
