### ISSUE TITLE
Handle number fractions in json that are not enclosed in quotes.

### ISSUE THREAD

**Issue by paulb-instacart** [mangiucugna/json_repair#27]
**Is your feature request related to a problem? Please describe.**
Code currently does not handle: '{"key": 1/3}' --> it will currently mess up the parsing of the rest of the json string. It will treat the "1" as the value, and the "3" as the next key and swap the keys and values for the rest of the json. 
{"key1": 1/3, "key2": 1, "key3": "value3", "key4": "value4"}'
{'key1': 1, 3: 'key2', 1: 'key3', 'value3': 'key4'}

What I would like instead is '{"key": "1/3"}'. 

This original json output of '{"key": 1/3}' is a response I have received from an LLM. 

**Describe the solution you'd like**
I would like it to output the fraction as a string.

**Describe alternatives you've considered**

**Additional context**

**Comment by mangiucugna** [comment]
good catch! Thanks for pushing a fix, I will release 0.15.2 now
