### ISSUE TITLE
Handle missing comma

### ISSUE THREAD

**Issue by liangjs** [mangiucugna/json_repair#36]
**Describe the bug**
Can we handle missing comma when parsing dict?

**To Reproduce**
```python
json_repair.loads('''{
  "number": 1,
  "reason": "According..."
  "ans": "YES"
}''')
```
This code produces `{'number': 1, 'reason': 'According..."\n  "ans": "YES'}`.
But we expect `{'number': 1, 'reason': 'According...', 'ans': 'YES'}`.

**Comment by mangiucugna** [comment]
Thanks @liangjs, this is a regression as I changed the way quotes are handled to support many more cases.
