### ISSUE TITLE
Price like numbers not properly parsed

### ISSUE THREAD

**Issue by GeraldWu23** [mangiucugna/json_repair#42]
**Describe the bug**
Price like number not properly parsed. 

**To Reproduce**
`from json_repair import repair_json
repair_json("{'price': [105,000.00']}")`

**Expected behavior**
return "{'price': ['105,000.00']}" (or return "{'price': [105,000.00]}", format doesn't matter since a quote is loss) 

**Screenshots**
<img width="549" alt="image" src="https://github.com/mangiucugna/json_repair/assets/27190172/2dff1758-9634-4c18-a351-62ebb3c1981b">

**Desktop (please complete the following information):**
 - Version Python==3.9.18 json_repair==0.10.1

**Comment by mangiucugna** [comment]
Thanks for reporting, I will release a fix now but be advised that in this case, due to the stray `'` it will be fixed a bit weirdly:

`{"price": ["105,000.00", "]}"]}`

**Comment by GeraldWu23** [comment]
thanks, it resolves my case
