### ISSUE TITLE
Parsing comments with float point number 

### ISSUE THREAD

**Issue by liangjs** [mangiucugna/json_repair#45]
Consider the following code:
```python
json_repair.loads("""{ \n "b": "xxxxx" // comment 1.2 \n }""")
```

It should be `{'b': 'xxxxx'}`.
But the library outputs `{'b': 'xxxxx', 0.2: ''}`.

**Comment by liangjs** [comment]
More generally, we can test with this code
```python
json_repair.loads("""{
  "b": "xxxxx", // comment a.b
  "c": "a"
}""")
```

It produces a weird result `{'b': 'xxxxx', '.': 'c": "a'}`

**Comment by mangiucugna** [comment]
Thanks for reporting, indeed the bug is subtle but produces those results. I am pushing a new version with the (quite trivial) fix and the new results, as tested in the new version, are:
```
{'b': 'xxxxx'}
{'b': 'xxxxx', 'c': 'a'}
```

**Comment by mangiucugna** [comment]
Hi, I tried this with the latest version of the library and I couldn't reproduce. I am pushing a fix because I noticed that there is a different edge case but I can't reproduce this specific edge case using latest.

**Comment by liangjs** [comment]
Thanks. After checking out to the latest version, it is fixed.
