### ISSUE TITLE
[Bug]: json_repair does not work for following json

### ISSUE THREAD

**Issue by Laserlicht** [mangiucugna/json_repair#47]
Thanks for the library! :)

### Version of the library

0.20.0

### Describe the bug

After parsing the "graphics" object is not in the correct hierarchy.

And also the bonus with bool variables does not seems to parsed correctly.

### How to reproduce

Use json_repair.loads() with following json:
https://raw.githubusercontent.com/vcmi-mods/tides-of-war/vcmi-1.5/Mods/alternative-creatures/content/config/creatures/rampart/dryad.json

Compare object for example with json5 library output.

**Comment by mangiucugna** [comment]
Thanks for reporting, this was way trickier to figure out than I anticipated but it was a couple of small stupid edge case. I am pushing 0.20.1 out now

**Comment by Laserlicht** [comment]
Thanks for the ultra fast response. Looks good now. :)
