### ISSUE TITLE
Not support pytohn3.7

### ISSUE THREAD

**Issue by cool9203** [mangiucugna/json_repair#5]
**Describe the bug**

First sorry for my english.

This package used `:=` operator. 
[The operator start with `python3.8`](https://docs.python.org/3.8/whatsnew/3.8.html#assignment-expressions), so not support `python3.7`.

But `python3.7` will install success, and `pyproject.toml` set support `python3.7`.
Should set to `python3.8` or not use `:=` opeartor.

https://github.com/mangiucugna/json_repair/blob/eaf67ab83cafe6fb8a8399414a2c61718c8e94d7/pyproject.toml#L14

**To Reproduce**
1. Use `python3.7`.
2. Use this package
3. See error

**Expected behavior**
Should run success in `python3.7` or install failed in `python3.7`.

**Screenshots**
![image](https://github.com/mangiucugna/json_repair/assets/29609607/67f69758-7500-4d5d-aa31-cb96d6b14e02)

 - OS: windows10
 - Python-Version: 3.7

**Additional context**

Example code(in python3.7):

```python
import json

from json_repair import repair_json

json_string = r'{"a": 1 }{}'

json.loads(repair_json(json_string))
```

**Comment by mangiucugna** [comment]
Thank you for your report, I have added now a github action to test across multiple python versions. I am releasing now 0.1.10 to be compatible with python 3.7
