### ISSUE TITLE
[Bug]: Does not add missing comma in an array of strings but works fine with array of numbers

### ISSUE THREAD

**Issue by SumitRathor002** [mangiucugna/json_repair#55]
### Version of the library

0.25.1

### Describe the bug

Broken Json : 
{
    "name": "Mike",
    "age": 29,
    "is_student": "false",
    "bio": "Loves to read and play guitar",
    "hobbies": ["Reading" "Playing guitar" "Swimming"]
}
Repaired Json:
{
    "age": 29,
    "bio": "Loves to read and play guitar",
    "hobbies": [
        "Reading\" \"Playing guitar\" \"Swimming"
    ],
    "is_student": "false",
    "name": "Mike"
}
This is not how the repaired json should look like , i was expecting it to look like the below one
{
    "age": 29,
    "bio": "Loves to read and play guitar",
    "hobbies": [
        "Reading", "Playing guitar" ,"Swimming"
    ],
    "is_student": "false",
    "name": "Mike"
}
Although the library works fine in the case of array of integer

### How to reproduce

{
    "name": "Mike",
    "age": 29,
    "is_student": "false",
    "bio": "Loves to read and play guitar",
    "hobbies": ["Reading" "Playing guitar" "Swimming"]
}

### Expected behavior

Broken Json : 
{
    "name": "Mike",
    "age": 29,
    "is_student": "false",
    "bio": "Loves to read and play guitar",
    "hobbies": ["Reading" "Playing guitar" "Swimming"]
}
Repaired Json:
{
    "age": 29,
    "bio": "Loves to read and play guitar",
    "hobbies": [
        "Reading\" \"Playing guitar\" \"Swimming"
    ],
    "is_student": "false",
    "name": "Mike"
}
This is not how the repaired json should look like , i was expecting it to look like the below one
{
    "age": 29,
    "bio": "Loves to read and play guitar",
    "hobbies": [
        "Reading", "Playing guitar" ,"Swimming"
    ],
    "is_student": "false",
    "name": "Mike"
}
Although the library works fine in the case of array of integer

**Comment by mangiucugna** [comment]
I have released 0.25.2 with the fix
