### ISSUE TITLE
[Feature Request]: Add support for `mypy`

### ISSUE THREAD

**Issue by JakeSummers** [mangiucugna/json_repair#64]
### Describe the solution you'd like

It looks like this library has some amount of python types.  

Right now if I have this code in my repo: 

```python
from json_repair import repair_json
```

And then I run `mypy`, I get: 

```
error: Skipping analyzing "json_repair": module is installed, but missing library stubs or py.typed marker  [import-untyped]
```

### Context

Type safe code is good code.  :)

**Comment by mangiucugna** [comment]
Good catch, I have released 0.28.0 and tested it against mypy and I see no warnings :)
