### ISSUE TITLE
[Bug]: issue with parsing rust code in JSON

### ISSUE THREAD

**Issue by pchalasani** [mangiucugna/json_repair#72]
### Version of the library

0.29.4

### Describe the bug

In the example below the value of `content` field is a piece of rust code, it starts with double-quotes (`"`) and ends with double-quotes. 
The repaired json should simply escape the newlines within the string, and the `content` field value should be the entire code, but I get unexpected results as you see below.

```
In [21]: s = '''
    ...: {
    ...:     "request": "write_file_tool",
    ...:     "file_path": "src/lib.rs",
    ...:     "content": "use std::cmp::Ordering;
    ...:
    ...: pub struct GuessGame {
    ...:     secret_number: u32,
    ...: }
    ...:
    ...: impl GuessGame {
    ...:     pub fn new() -> Self {
    ...:         GuessGame { secret_number: 42 }
    ...:     }
    ...:
    ...:     pub fn check_guess(&self, guess: u32) -> String {
    ...:         match guess.cmp(&self.secret_number) {
    ...:             Ordering::Less => String::from(\"Too low!\"),
    ...:             Ordering::Greater => String::from(\"Too high!\"),
    ...:             Ordering::Equal => String::from(\"You got it!\"),
    ...:         }
    ...:     }
    ...: }
    ...: "
    ...: }
    ...: '''

In [22]: repair_json(s)
Out[22]: '[{"request": "write_file_tool", "file_path": "src/lib.rs", "content": "use std::cmp::Ordering;\\n\\npub struct GuessGame {\\n    secret_number: u32"}, {"secret_number": 42}, {"Ordering": "Less => String::from(", "low!": "Ordering::Greater => String::from(", "high!": "Ordering::Equal => String::from(", "it!": ""}]'

```

### How to reproduce

see above.

### Expected behavior

The repaired json should simply escape the newlines within the string, and the `content` field value should be the entire code, but I get unexpected results as you see below.

EDITED - sorry for the multiple edits - I now have the actual failure case shown above.

**Comment by pchalasani** [comment]
btw I really like this library for handling  JSONs from weak LLMs, but ran into the above issue.

**Comment by pchalasani** [comment]
(just edited the example slightly)

**Comment by pchalasani** [comment]
I was having trouble creating a good minimal failure to illustrate the actual failure I was having, but the above example actually works (my example input was wrong). I'll try to make a real failing example shortly.

**Comment by pchalasani** [comment]
Here's a link to the playground where I tried it:

https://mangiucugna.github.io/json_repair/?json=%257B%250A%2520%2520%2520%2520%2522request%2522%253A%2520%2522write_file_tool%2522%252C%250A%2520%2520%2520%2520%2522file_path%2522%253A%2520%2522src%252Flib.rs%2522%252C%250A%2520%2520%2520%2520%2522content%2522%253A%2520%2522use%2520std%253A%253Acmp%253A%253AOrdering%253B%250A%250Apub%2520struct%2520GuessGame%2520%257B%250A%2520%2520%2520%2520secret_number%253A%2520u32%252C%250A%257D%250A%250Aimpl%2520GuessGame%2520%257B%250A%2520%2520%2520%2520pub%2520fn%2520new%28%29%2520-%253E%2520Self%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520GuessGame%2520%257B%2520secret_number%253A%252042%2520%257D%250A%2520%2520%2520%2520%257D%250A%250A%2520%2520%2520%2520pub%2520fn%2520check_guess%28%2526self%252C%2520guess%253A%2520u32%29%2520-%253E%2520String%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520match%2520guess.cmp%28%2526self.secret_number%29%2520%257B%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520Ordering%253A%253ALess%2520%253D%253E%2520String%253A%253Afrom%28%255C%2522Too%2520low%21%255C%2522%29%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520Ordering%253A%253AGreater%2520%253D%253E%2520String%253A%253Afrom%28%255C%2522Too%2520high%21%255C%2522%29%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520%2520Ordering%253A%253AEqual%2520%253D%253E%2520String%253A%253Afrom%28%255C%2522You%2520got%2520it%21%255C%2522%29%252C%250A%2520%2520%2520%2520%2520%2520%2520%2520%257D%250A%2520%2520%2520%2520%257D%250A%257D%250A%2522%250A%257D

**Comment by mangiucugna** [comment]
Hi! I found the issue in the parser so I will release a new version shortly, one note for your use case though. You need to use **realstrings** to pass the escaping correctly:

```
json_to_fix = r"""
{
    "request": "write_file_tool",
    "file_path": "src/lib.rs",
    "content": "use std::cmp::Ordering;

pub struct GuessGame {
    secret_number: u32
}

impl GuessGame {
    pub fn new() -> Self {
        GuessGame { secret_number: 42 }
    }

    pub fn check_guess(&self, guess: u32) -> String {
        match guess.cmp(&self.secret_number) {
            Ordering::Less => String::from(\"Too low!\"),
            Ordering::Greater => String::from(\"Too high!\"),
            Ordering::Equal => String::from(\"You got it!\"),
        }
    }
}
"
}
"""

pprint(json_repair.loads(json_to_fix))
```

Output:
```
{'content': 'use std::cmp::Ordering;\n'
            '\n'
            'pub struct GuessGame {\n'
            '    secret_number: u32\n'
            '}\n'
            '\n'
            'impl GuessGame {\n'
            '    pub fn new() -> Self {\n'
            '        GuessGame { secret_number: 42 }\n'
            '    }\n'
            '\n'
            '    pub fn check_guess(&self, guess: u32) -> String {\n'
            '        match guess.cmp(&self.secret_number) {\n'
            '            Ordering::Less => String::from("Too low!"),\n'
            '            Ordering::Greater => String::from("Too high!"),\n'
            '            Ordering::Equal => String::from("You got it!"),\n'
            '        }\n'
            '    }\n'
            '}',
 'file_path': 'src/lib.rs',
 'request': 'write_file_tool'}
```
The presence of `\n` is a bit of a funkyness of how escaping works but shouldn't be a problem for you to just simply remove those are process them appropriately. Parsing Rust is particularly difficult because the syntax resembles json quite a bit.
