### ISSUE TITLE
[Bug]: Handling LaTeX inside a string

### ISSUE THREAD

**Issue by sreeramcoder** [mangiucugna/json_repair#74]
### Version of the library

https://mangiucugna.github.io/json_repair/

### Describe the bug

I see the issue in the demo link. If the json contains a string with LaTeX expressions, the backslash is removed (backslash is needed for LaTeX). Instead it is recommended to escape the backslash.

### How to reproduce

For input
`{
  "content": [
    {
      "topic_text": " $$\mathrm{F}_1$$ and $$\mathrm{F}_2$$."
    }
  ]
}
`, output is 
`{
    "content": [
        {
            "topic_text": " $$mathrm{F}_1$$ and $$mathrm{F}_2$$."
        }
    ]
}`

### Expected behavior

The expected output is 
`{
    "content": [
        {
            "topic_text": " $$\\mathrm{F}_1$$ and $$\\mathrm{F}_2$$."
        }
    ]
}`

**Comment by mangiucugna** [comment]
I have release 0.29.7 and also reloaded the demo site
