### ISSUE TITLE
[Bug]: unquoted value strings with brackets lose first closing bracket and any text after it

### ISSUE THREAD

**Issue by slidedrum** [mangiucugna/json_repair#76]
### Version of the library

0.29.7

### Describe the bug

When a repairing a key/value pair that is unquoted, it treats them both as strings, as it should.  However, if the value string contains a closing curly bracket } then it cuts off the rest of the string.  The code below prints 

{'text': 'words{words in brackets'}

I am not sure if changing this would break some other edge case, but it is making this package unuseable for me in my use case.  I think it is assuming that the next closing bracket closes out the json object.  It should keep track of any nested brackets inside the unquoted string so that it breaks at the correct closing bracket.

### How to reproduce

import json_repair
input_str = '{text:words{words in brackets}more words}'
output_str = json_repair.loads(input_str)
print(output_str)

### Expected behavior

It should print

{'text': 'words{words in brackets}more words'}

**Comment by mangiucugna** [comment]
I understand your use case but the problem is that the json in your example is valid, so the library isn’t really trying to fix anything here.

Maybe you have a different or larger example I could take a look at?

**Comment by mangiucugna** [comment]
sorry my bad, I was looking at your initial explanation and not how to reproduce. I now see the issue.

**Comment by mangiucugna** [comment]
I have released a new version with the fix for your case. Thanks for reporting

**Comment by slidedrum** [comment]
Thank you so much for the quick fix!  This change works in most cases, however I found another case where this does not work as expected.  When the brackets do not have any words after it, or there is a single letter after the brackets, the trailing bracket and the single letter is lost.  For example

`'{text:words{words in brackets}}'`
`'{text:words{words in brackets}m}'`

Both result in 

`{"text": "words{words in brackets"}`

They should print 

`{"text": "words{words in brackets}"}`
`{"text": "words{words in brackets}m"}`

**Comment by mangiucugna** [comment]
Thanks for pointing this out, I have released a new version now with this fix
