### ISSUE TITLE
[Feature Request]: Support utf-8 characters

### ISSUE THREAD

**Issue by kinga-marszalkowska** [mangiucugna/json_repair#79]
### Describe the solution you'd like

I like this library a lot! The only thing it's missing is the ability to save to utf-8 encoded string. Whenever I use repair_json(my_string) I get a fixed json string but with my characters replaced by `\uoof3` for example

### Context

I would like to parse jsons in languages different than English.

**Comment by mangiucugna** [comment]
Hi! This can be achieved by passing the parameter `ensure_ascii=False`.

Let me know if that works for you.
