### ISSUE TITLE
Infinite Loop when the input is `{"`

### ISSUE THREAD

**Issue by brianineza01** [mangiucugna/json_repair#8]
**Describe the bug**
I was trying the json response streaming from openai api and fix it using this library. When the json input was `{"` it got my program stuck for some reason. After deep investigation, I found it was an infinite loop in this library. Attached below are some screenshots with what's happening and the function that it's happening in. I added some `print()` in the library code to check what's happening.

**To Reproduce**
1. Import the library
2. make your JSON string `{"`
3. use the `repair_json` function from the library
4. You will have a stuck program with an infinite loop.

**Expected behavior**
Should throw an error or have an empty object like `{}`.

**Screenshots**
![CleanShot 2023-11-22 at 07 01 50@2x](https://github.com/mangiucugna/json_repair/assets/60552218/6b2b7096-6d5e-473a-ae7b-84c89b7afee6)
![CleanShot 2023-11-22 at 07 00 37@2x](https://github.com/mangiucugna/json_repair/assets/60552218/864a11a1-1d85-4065-9c4b-2d4a2d6bc66f)

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma
 - Version 0.4.1

**Comment by mangiucugna** [comment]
Thanks for reporting the bug, I have released 0.4.2 with the fix
