### ISSUE TITLE
[Feature Request]: Support parsing LLM output containing <triple backticks>json{"field": value}<triple backticks>

### ISSUE THREAD

**Issue by rohitgarud** [mangiucugna/json_repair#84]
### Describe the solution you'd like

Something like this can be implemented:
```python
if "```json" in completion:
    match = re.search(r"```json(.*?)```", completion, re.DOTALL)
    if match:
        completion = match.group(1).strip()
```

### Context

Smaller LLMs tend to return JSON in ```json``` blocks

**Comment by mangiucugna** [comment]
Hi Rohit, this is pretty much outside of the scope of this library. The idea is to fix json not to generally parse text, moreover what you want can be achieved with a regular expression to isolate the text and then pass that text to json_repair.

Cheers

**Comment by rohitgarud** [comment]
> Hi Rohit, this is pretty much outside of the scope of this library. The idea is to fix json not to generally parse text, moreover what you want can be achieved with a regular expression to isolate the text and then pass that text to json_repair.
> 
> Cheers

Makes sense, thank you
