### ISSUE TITLE
[Bug]: Invalid parsing of strings that contain a colon (:)

### ISSUE THREAD

**Issue by emiraga** [mangiucugna/json_repair#87]
### Version of the library

0.33.0

### Describe the bug

Invalid parsing of the partial JSON `{"content":"test1, test2. test3: test4`

### How to reproduce

```
>>> print(json_repair.loads('{"content":"test1, test2. test3: test4'))
{'content': 'test1', 'test3': 'test4'}
```

### Expected behavior

```
>>> print(json_repair.loads('{"content":"test1, test2. test3:'))
{'content': 'test1, test2. test3: test4'}
```

**Comment by mangiucugna** [comment]
Hi, could you provide an example of the actual llm output so I can see it in context?
This example is too narrow to understand what really should be the right behavior, as json is often ambigous and this repair action is working as intended in this case.

**Comment by emiraga** [comment]
OpenAI API is asked to produce structured output, https://platform.openai.com/docs/guides/structured-outputs one of the fields is called "content" for which LLM produces paragraphs of text and sometimes it lists items with description as markdown. (Example at the bottom)

I stream that response, we parse **partial replies** from the OpenAI. I switched to using https://github.com/matthewdeanmartin/untruncate_json/ which might be more suitable for this use case.

```
{"content": "Introduction\n - **One**: Description\n - **Two**: Description", "references": []}
```

**Comment by mangiucugna** [comment]
I see, if you are using structured output you are guaranteed to always receive a valid json conform to the schema so this library is indeed the wrong choice for that use case.
