### ISSUE TITLE
[Feature Request]: SyntaxError: invalid character '、' (U+3001)，For the sick json returned by LLMs, the semantics in the Chinese environment need to be improved 

### ISSUE THREAD

**Issue by Jovi-qiu** [mangiucugna/json_repair#88]
### Describe the solution you'd like

For example, there are symbols such as double quotation marks in the text, which are not very completely removed，Hopefully it can be improved in the future

### Context

This is one of the most important and easier to ignore scenarios in many scenarios

**Comment by mangiucugna** [comment]
Hi! 
Can you provide an example of a text that causes the issue? 
Have you also set `ensure_ascii=False`? that is important for text in non-latin characters

**Comment by mangiucugna** [comment]
for context, I tried with the character you mention in the title and I cannot reproduce the error

**Comment by Jovi-qiu** [comment]
Because the text content is sensitive, it is not easy to disclose, but I can forge it. For example:
“来源”:"不仅有“咖啡、葡萄”还有百年孤独"



---- Replied Message ----
| From | Stefano ***@***.***> |
| Date | 12/25/2024 20:28 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mangiucugna/json_repair] [Feature Request]: SyntaxError: invalid character '、' (U+3001)，For the sick json returned by LLMs, the semantics in the Chinese environment need to be improved  (Issue #88) |

for context, I tried with the character you mention in the title and I cannot reproduce the error

**Comment by mangiucugna** [comment]
HI! Thanks for providing the example, I cannot seem to reproduce the issue:

```
txt = """{“来源”:"不仅有“咖啡、葡萄”还有百年孤独"}"""
print(repair_json(txt, ensure_ascii=False))
```

`{"来源": "不仅有“咖啡、葡萄”还有百年孤独"}`

**Comment by Jovi-qiu** [comment]
I know the reason for triggering this. I didn't add """ to cause it. Thank you for your patient answer! Thank you!



---- 回复的原邮件 ----
| 发件人 | Stefano ***@***.***> |
| 日期 | 2024年12月26日 15:04 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [mangiucugna/json_repair] [Feature Request]: SyntaxError: invalid character '、' (U+3001)，For the sick json returned by LLMs, the semantics in the Chinese environment need to be improved  (Issue #88) |

HI! Thanks for providing the example, I cannot seem to reproduce the issue:

txt = """{“来源”:"不仅有“咖啡、葡萄”还有百年孤独"}"""
print(repair_json(txt, ensure_ascii=False))


{"来源": "不仅有“咖啡、葡萄”还有百年孤独"}
