### ISSUE TITLE
[Bug]: json_repair() fails to generate dict() 

### ISSUE THREAD

**Issue by corncup** [mangiucugna/json_repair#90]
### Version of the library

0.34.0

### Describe the bug

json_repair() fails to parse a specific json-formatted text. Instead of returning a dict, it returns a list with an extra ['str'] element. 

### How to reproduce

    ss = """
```json
{
    "summary": "Wi-Fi connectivity issues and security concerns",
    "security_aspects": [
        "Unauthorized access to system resources",
        "Unsecured network connections",
        "Insufficient packet filtering",
        "Lack of encryption on wireless transmissions"
    ]
}
```

Note: The `security_aspects` list is formatted as a valid Python list[str] and includes potential security concerns related to the Wi-Fi connectivity issues mentioned in the log output.
"""
    ## 
    res = json_repair.loads(ss)
    print(res)
    
    ## The (WRONG) result is:
    
    [{'summary': 'Wi-Fi connectivity issues and security concerns', 'security_aspects': ['Unauthorized access to system resources', 'Unsecured network connections', 'Insufficient packet filtering', 'Lack of encryption on wireless transmissions']}, ['str']]

### Expected behavior

It should return:

{'summary': 'Wi-Fi connectivity issues and security concerns',
 'security_aspects': ['Unauthorized access to system resources', 'Unsecured network connections', 'Insufficient packet filtering', 'Lack of encryption on wireless transmissions']
}

**Comment by mangiucugna** [comment]
Hi, while this might look weird, the library it's working as intended. 
json_repair will return an array with multiple objects if it detects multiple valid objects in the json. And in this case ['str'] is detected as an array with a string element in it.
