### ISSUE TITLE
[Bug]: issue when Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by aradelli** [mangiucugna/json_repair#91]
### Version of the library

0.34.0

### Describe the bug

When the closing double quotes are missing in a property, the first char of the value is truncated and the : are included in the key.

### How to reproduce

```
print(json_repair.loads('{"key: "value"}'))
{'key:': 'alue'}
```

### Expected behavior

`{'key': 'value'}`

**Comment by mangiucugna** [comment]
I can't believe this case was never in my tests but indeed it wasn't.
